export type ArchiveProject = {
  id: string;
  title: string;
  category: "EdTech Games" | "AI & Python Tools" | "Academic" | "UI & Apps" | "Juegos EdTech" | "UI y Apps" | "Académico" | "GitHub Auto-Sync" | string;
  tech: string[];
  github: string;
  link?: string;
  year: string;
  description?: string;
  problem?: string;
  solution?: string;
};

export const archiveDataEN: ArchiveProject[] = [
  {
    id: "cpe",
    title: "CEFR Mock Exams",
    category: "SaaS Products",
    tech: ["Next.js", "TypeScript", "Supabase", "Groq", "Gemini", "Stripe"],
    github: "https://github.com/antoniotagaruma8",
    link: "https://cpev2.vercel.app/",
    year: "2026",
    description: "A full-stack AI English exam platform with automated generation across 5 CEFR levels.",
    problem: "Students preparing for Cambridge exams lack affordable, high-quality practice tests that adapt to their level.",
    solution: "An AI-powered exam generator using multiple LLMs (Gemini + Groq) that creates unique, level-appropriate practice tests with Stripe-integrated payments.",
  },
  {
    id: "cv-builder",
    title: "AI CV Builder",
    category: "SaaS Products",
    tech: ["Next.js", "Supabase", "Stripe", "jsPDF", "Gemini API"],
    github: "https://github.com/antoniotagaruma8",
    link: "/en/coming-soon",
    year: "2026",
    description: "An intelligent SaaS platform that dynamically tailors CVs to specific job descriptions using AI.",
    problem: "Job seekers waste hours manually rewriting their CV for each application, often missing ATS optimization.",
    solution: "A Gemini AI-powered tool that analyzes job descriptions and automatically rewrites CV bullet points, optimizing for Applicant Tracking Systems with instant PDF export.",
  },
  {
    id: "carta-clara",
    title: "Carta Clara",
    category: "SaaS Products",
    tech: ["Next.js", "Supabase", "Stripe", "Groq AI", "Tailwind CSS"],
    github: "https://github.com/antoniotagaruma8",
    link: "/en/coming-soon",
    year: "2026",
    description: "A hardware-enabled SaaS for tourist-heavy restaurants with kiosk mode, receipt printing, and AI consulting.",
    problem: "Small restaurants in tourist zones struggle with multilingual menus, order management, and lack business analytics tools.",
    solution: "A zero-risk 'Partner Contract' model providing a KDS ordering loop, automated receipt printing, and an AI-powered CFO dashboard for real-time business consulting.",
  },
  {
    id: "vocabulary-race",
    title: "Vocabulary Race TV",
    category: "EdTech Games",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/vocabulary-race-activity",
    link: "https://vocabulary-race-activity.vercel.app",
    year: "2024",
    description: "A high-energy, TV-style vocabulary racing game for the classroom.",
    problem: "Vocabulary reviews often lack the competitive excitement needed to keep students fully engaged.",
    solution: "A dynamic, gamified interface that simulates a TV game show environment, encouraging rapid vocabulary recall under time pressure.",
  },
  {
    id: "philippine-education",
    title: "Philippine Education System",
    category: "Academic",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/philippine-education",
    link: "https://philippineeducation.vercel.app",
    year: "2024",
    description: "An interactive presentation detailing the history and structure of the Philippine Education System.",
    problem: "Static slide decks often fail to keep students engaged during long historical lectures.",
    solution: "A custom-built web presentation with interactive timelines and dynamic content reveals.",
  },
  {
    id: "photo-description",
    title: "Photo Description Activity",
    category: "EdTech Games",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/photo-description-activity",
    link: "https://photo-description-activity.vercel.app",
    year: "2024",
    description: "A Gen-Z themed interactive activity for practicing English photo descriptions.",
    problem: "Students struggle with the vocabulary and structure required for Cambridge speaking exams (Part 2).",
    solution: "A timed, gamified interface that prompts students to describe dynamic images using target vocabulary.",
  },
  {
    id: "debate-spark",
    title: "Debate Spark",
    category: "EdTech Games",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/debate-spark",
    link: "https://debate-lovat.vercel.app",
    year: "2024",
    description: "A digital debate platform that automatically assigns sides and tracks points.",
    problem: "Classroom debates often get messy with manual timing and scoring.",
    solution: "Built a fast, keyboard-accessible web app to streamline debate mechanics.",
  },
  {
    id: "thisisnot-a",
    title: "This is not a...",
    category: "EdTech Games",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/thisisnot-a-",
    link: "https://thisisnot-a.vercel.app",
    year: "2024",
    description: "A creative browser-based drawing and guessing game.",
    problem: "Remote teams and online classrooms lack quick, engaging icebreaker activities.",
    solution: "A lightweight, interactive canvas game that encourages quick thinking and creativity.",
  },
  {
    id: "spanishwithandwisdom",
    title: "Spanish Wit & Wisdom!",
    category: "EdTech Games",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/spanishtoenglish",
    link: "https://spanishwithandwisdom.vercel.app",
    year: "2024",
    description: "An interactive learning application focused on Spanish idioms and cultural expressions.",
    problem: "Traditional language learning often ignores colloquialisms, leaving students sounding unnatural.",
    solution: "A gamified platform that teaches native-like Spanish expressions through contextual quizzes.",
  },
  {
    id: "esoslpv2",
    title: "ESOSLPv2",
    category: "UI & Apps",
    tech: ["Streamlit", "FastAPI", "Python", "Gemini 2.0", "RAG", "FAISS", "PostgreSQL", "Google OAuth"],
    github: "https://github.com/antoniotagaruma8/esoslpv2",
    link: "https://esosl-pv2.vercel.app",
    year: "2024",
    description: "An AI-powered curriculum design and smart lesson planner for educators.",
    problem: "Teachers spend hours manually drafting lesson plans and aligning them with educational standards.",
    solution: "A centralized dashboard that leverages AI to instantly generate structured, standard-aligned lesson plans.",
  },
  {
    id: "word-snake",
    title: "WordSnake",
    category: "EdTech Games",
    tech: ["JavaScript", "HTML", "CSS"],
    github: "https://github.com/antoniotagaruma8/WordSnake",
    link: "https://word-snake-pi.vercel.app",
    year: "2026",
    description: "A fast-paced category sprint game designed to test vocabulary recall.",
    problem: "Vocabulary brainstorming exercises can often feel repetitive and uninspiring for language learners.",
    solution: "A competitive, timed web game that challenges students to recall words within specific categories under pressure.",
  },
  {
    id: "conditionals-game",
    title: "Conditionals Game",
    category: "EdTech Games",
    tech: ["JavaScript", "DOM Manipulation"],
    github: "https://github.com/antoniotagaruma8/ConditionalsGame",
    link: "https://conditionals-game.vercel.app",
    year: "2026",
    description: "A classroom arcade game designed to teach English conditionals.",
    problem: "Grammar exercises for conditionals are often dry, repetitive worksheet tasks.",
    solution: "An interactive, retro-style web game that makes drilling conditional clauses competitive and fun.",
  },
  {
    id: "reported-speech",
    title: "Reported Speech Activity",
    category: "EdTech Games",
    tech: ["JavaScript"],
    github: "https://github.com/antoniotagaruma8/ReportedSpeech",
    link: "https://reported-speech-kohl.vercel.app",
    year: "2026",
    description: "A news-themed classroom game for mastering reported speech.",
    problem: "Students find the tense-shifting rules of reported speech confusing and counterintuitive.",
    solution: "A roleplay-style interface where students act as journalists converting direct quotes into reported news.",
  },
  {
    id: "passive-voice",
    title: "Passive Voice Activity",
    category: "EdTech Games",
    tech: ["JavaScript"],
    github: "https://github.com/antoniotagaruma8/passivevoiceactivity",
    link: "https://passivevoiceactivity.vercel.app",
    year: "2026",
    description: "A 'Tug of War' style game for practicing passive vs active voice.",
    problem: "Learners frequently mix up the subject and object when forming passive sentences.",
    solution: "A visual tug-of-war mechanic that reinforces the grammatical shift between active and passive structures.",
  },
  {
    id: "follow-frog",
    title: "Follow The Frog",
    category: "EdTech Games",
    tech: ["JavaScript", "HTML"],
    github: "https://github.com/antoniotagaruma8/FollowTheFrogActivity",
    link: "https://follow-the-frog-activity.vercel.app",
    year: "2026",
    description: "An interactive comprehension activity based on the 'Follow the Frog' environmental awareness campaign.",
    problem: "Traditional listening comprehension exercises on sustainability can feel disconnected from real-world media.",
    solution: "A gamified web lesson that uses the popular video campaign to test comprehension and vocabulary in an engaging format.",
  },
  {
    id: "loan-word",
    title: "Loan Word Detectives",
    category: "EdTech Games",
    tech: ["JavaScript", "HTML"],
    github: "https://github.com/antoniotagaruma8/LoanWordDetectives",
    link: "https://loan-word-detectives.vercel.app",
    year: "2026",
    description: "An engaging linguistic game where students identify foreign loan words in English.",
    problem: "Students often struggle to recognize etymological roots, which can hinder advanced vocabulary acquisition.",
    solution: "A detective-themed web game that makes exploring word origins and etymology interactive and rewarding.",
  },
  {
    id: "ph-cold-war",
    title: "PhDuringColdWar (Word Game)",
    category: "EdTech Games",
    tech: ["JavaScript", "HTML"],
    github: "https://github.com/antoniotagaruma8/PhDuringColdWar",
    link: "https://ph-during-cold-war.vercel.app",
    year: "2026",
    description: "An interactive historical exploration game about the Philippines during the Cold War.",
    problem: "Students often find textbook history lessons about the Cold War era dry and difficult to connect with.",
    solution: "A declassified-archives themed interactive web experience that brings historical events to life through gamified exploration.",
  },
  {
    id: "lesson-hub",
    title: "Classes and Lessons Hub",
    category: "UI & Apps",
    tech: ["TypeScript", "Next.js"],
    github: "https://github.com/antoniotagaruma8/lesson-hub",
    link: "https://classhub-seven.vercel.app",
    year: "2026",
    description: "A centralized archive and management dashboard for classroom resources.",
    problem: "Educational materials become fragmented across local drives and cloud storage over a semester.",
    solution: "A cleanly organized Next.js portal that acts as a single source of truth for students and teachers.",
  },
  {
    id: "mooc-final",
    title: "MOOC Final Project",
    category: "Academic",
    tech: ["SCSS", "HTML"],
    github: "https://github.com/antoniotagaruma8/MOOCFinalProject",
    link: "https://mooc-final-project.vercel.app",
    year: "2026",
    description: "A comparative education final project analyzing global teaching methodologies.",
    problem: "Synthesizing large volumes of comparative educational data into a readable format is challenging.",
    solution: "A responsive, SCSS-styled academic portal that presents complex research clearly and beautifully.",
  },
  {
    id: "tech-education",
    title: "Tech In Education Blog",
    category: "Academic",
    tech: ["HTML", "CSS"],
    github: "https://github.com/antoniotagaruma8/techineducation",
    link: "https://techineducation.vercel.app",
    year: "2026",
    description: "An interactive presentation on AI-assisted web development in education.",
    problem: "Educators lack accessible resources on how to integrate modern AI tools into their teaching workflow.",
    solution: "A dynamic, slide-based web application that visually demonstrates practical AI integrations.",
  },
  {
    id: "pdf-editor",
    title: "Interactive PDF Editor",
    category: "UI & Apps",
    tech: ["HTML5", "Canvas API", "PDF.js", "Fabric.js"],
    github: "https://github.com/antoniotagaruma8",
    link: "/en/coming-soon",
    year: "2026",
    description: "A lightweight, zero-installation browser tool for projecting and annotating PDF worksheets on smart boards.",
    problem: "Teachers need to annotate PDFs in class but lack access to expensive proprietary software on school computers.",
    solution: "A client-side PDF renderer with a transparent Fabric.js drawing overlay for real-time annotation without any server uploads.",
  },
  {
    id: "interactive-drawing",
    title: "Interactive Drawing Board",
    category: "UI & Apps",
    tech: ["HTML5", "Canvas API", "PointerEvents API"],
    github: "https://github.com/antoniotagaruma8",
    link: "/en/coming-soon",
    year: "2026",
    description: "A touch-optimized digital whiteboard designed for primary education smart boards.",
    problem: "Commercial whiteboard software is too heavy and laggy for young children's rapid finger strokes on school hardware.",
    solution: "A zero-latency Canvas-based drawing app with simplified, color-coded controls designed for young learners' motor skills.",
  },
  {
    id: "trivia-bingo",
    title: "EdTech Trivia Bingo",
    category: "EdTech Games",
    tech: ["Node.js", "Socket.io", "Gemini AI", "Express"],
    github: "",
    link: "",
    year: "2026",
    description: "A real-time multiplayer trivia bingo game with AI-generated curriculum-aligned questions.",
    problem: "Teachers need engaging assessment tools that combine competitive gameplay with curriculum-relevant content.",
    solution: "A WebSocket-powered bingo platform where Gemini AI dynamically generates trivia questions on any topic for live classroom sessions.",
  }
];

export const archiveDataES: ArchiveProject[] = [
  {
    id: "cpe",
    title: "Exámenes CEFR Simulados",
    category: "Productos SaaS",
    tech: ["Next.js", "TypeScript", "Supabase", "Groq", "Gemini", "Stripe"],
    github: "https://github.com/antoniotagaruma8",
    link: "https://cpev2.vercel.app/",
    year: "2026",
    description: "Una plataforma completa de exámenes de inglés con IA con generación automatizada en 5 niveles CEFR.",
    problem: "Los estudiantes que se preparan para los exámenes de Cambridge carecen de tests de práctica asequibles y de alta calidad que se adapten a su nivel.",
    solution: "Un generador de exámenes impulsado por IA que utiliza múltiples LLMs (Gemini + Groq) para crear tests de práctica únicos y apropiados al nivel con pagos integrados de Stripe.",
  },
  {
    id: "cv-builder",
    title: "AI CV Builder",
    category: "Productos SaaS",
    tech: ["Next.js", "Supabase", "Stripe", "jsPDF", "Gemini API"],
    github: "https://github.com/antoniotagaruma8",
    link: "/es/coming-soon",
    year: "2026",
    description: "Una plataforma SaaS inteligente que adapta dinámicamente los CVs a descripciones de trabajo específicas usando IA.",
    problem: "Los buscadores de empleo pierden horas reescribiendo manualmente su CV para cada solicitud, a menudo sin optimización ATS.",
    solution: "Una herramienta impulsada por Gemini AI que analiza las descripciones de trabajo y reescribe automáticamente los puntos del CV, optimizando para los Sistemas de Seguimiento de Candidatos con exportación PDF instantánea.",
  },
  {
    id: "carta-clara",
    title: "Carta Clara",
    category: "Productos SaaS",
    tech: ["Next.js", "Supabase", "Stripe", "Groq AI", "Tailwind CSS"],
    github: "https://github.com/antoniotagaruma8",
    link: "/es/coming-soon",
    year: "2026",
    description: "Un SaaS con hardware para restaurantes turísticos con modo kiosco, impresión de recibos y consultoría IA.",
    problem: "Los pequeños restaurantes en zonas turísticas luchan con menús multilingües, gestión de pedidos y carecen de herramientas de análisis de negocios.",
    solution: "Un modelo de 'Contrato de Socio' sin riesgo que proporciona un bucle de pedidos KDS, impresión automatizada de recibos y un panel de CFO impulsado por IA para consultoría empresarial en tiempo real.",
  },
  {
    id: "vocabulary-race",
    title: "Vocabulario Carrera TV",
    category: "Juegos EdTech",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/vocabulary-race-activity",
    link: "https://vocabulary-race-activity.vercel.app",
    year: "2024",
    description: "Un enérgico juego de carreras de vocabulario al estilo televisivo para el aula.",
    problem: "Las revisiones de vocabulario a menudo carecen del entusiasmo competitivo necesario para mantener a los estudiantes plenamente interesados.",
    solution: "Una interfaz dinámica y gamificada que simula el entorno de un programa de juegos de televisión, fomentando la recuperación rápida de vocabulario bajo presión de tiempo.",
  },
  {
    id: "philippine-education",
    title: "Sistema educativo filipino",
    category: "Académico",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/philippine-education",
    link: "https://philippineeducation.vercel.app",
    year: "2024",
    description: "Una presentación interactiva que detalla la historia y la estructura del sistema educativo filipino.",
    problem: "Las presentaciones de diapositivas estáticas a menudo no logran mantener a los estudiantes interesados ​​durante largas conferencias históricas.",
    solution: "Se revela una presentación web personalizada con líneas de tiempo interactivas y contenido dinámico.",
  },
  {
    id: "photo-description",
    title: "Foto Descripción Actividad",
    category: "Juegos EdTech",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/photo-description-activity",
    link: "https://photo-description-activity.vercel.app",
    year: "2024",
    description: "Una actividad interactiva temática de la Generación Z para practicar descripciones de fotografías en inglés.",
    problem: "Los estudiantes luchan con el vocabulario y la estructura necesarios para los exámenes orales de Cambridge (Parte 2).",
    solution: "Una interfaz gamificada y cronometrada que incita a los estudiantes a describir imágenes dinámicas utilizando vocabulario objetivo.",
  },
  {
    id: "debate-spark",
    title: "Chispa del debate",
    category: "Juegos EdTech",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/debate-spark",
    link: "https://debate-lovat.vercel.app",
    year: "2024",
    description: "Una plataforma de debate digital que asigna automáticamente bandos y rastrea puntos.",
    problem: "Los debates en el aula a menudo se vuelven complicados con el cronometraje y la puntuación manuales.",
    solution: "Creó una aplicación web rápida y accesible mediante teclado para optimizar la mecánica del debate.",
  },
  {
    id: "thisisnot-a",
    title: "Esto no es un...",
    category: "Juegos EdTech",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/thisisnot-a-",
    link: "https://thisisnot-a.vercel.app",
    year: "2024",
    description: "Un creativo juego de adivinanzas y dibujos basado en navegador.",
    problem: "Los equipos remotos y las aulas en línea carecen de actividades para romper el hielo rápidas y atractivas.",
    solution: "Un juego de lienzo ligero e interactivo que fomenta el pensamiento rápido y la creatividad.",
  },
  {
    id: "spanishwithandwisdom",
    title: "¡Ingenio y sabiduría en español!",
    category: "Juegos EdTech",
    tech: ["Next.js", "Vercel"],
    github: "https://github.com/antoniotagaruma8/spanishtoenglish",
    link: "https://spanishwithandwisdom.vercel.app",
    year: "2024",
    description: "Una aplicación de aprendizaje interactivo centrada en modismos y expresiones culturales españolas.",
    problem: "El aprendizaje de idiomas tradicional a menudo ignora los coloquialismos, lo que hace que los estudiantes parezcan poco naturales.",
    solution: "Una plataforma gamificada que enseña expresiones en español nativas a través de cuestionarios contextuales.",
  },
  {
    id: "esoslpv2",
    title: "ESOSLPv2",
    category: "UI y Apps",
    tech: ["Streamlit", "FastAPI", "Python", "Gemini 2.0", "RAG", "FAISS", "PostgreSQL", "Google OAuth"],
    github: "https://github.com/antoniotagaruma8/esoslpv2",
    link: "https://esosl-pv2.vercel.app",
    year: "2024",
    description: "Un diseño curricular impulsado por IA y un planificador de lecciones inteligente para educadores.",
    problem: "Los profesores pasan horas redactando manualmente planes de lecciones y alineándolos con los estándares educativos.",
    solution: "Un panel centralizado que aprovecha la IA para generar instantáneamente planes de lecciones estructurados y alineados con los estándares.",
  },
  {
    id: "word-snake",
    title: "Serpiente de palabra",
    category: "Juegos EdTech",
    tech: ["JavaScript", "HTML", "CSS"],
    github: "https://github.com/antoniotagaruma8/WordSnake",
    link: "https://word-snake-pi.vercel.app",
    year: "2026",
    description: "Un juego de sprint de categorías de ritmo rápido diseñado para evaluar la recuperación de vocabulario.",
    problem: "Los ejercicios de lluvia de ideas de vocabulario a menudo pueden resultar repetitivos y aburridos para los estudiantes de idiomas.",
    solution: "Un juego web competitivo y cronometrado que desafía a los estudiantes a recordar palabras dentro de categorías específicas bajo presión.",
  },
  {
    id: "conditionals-game",
    title: "Juego de condicionales",
    category: "Juegos EdTech",
    tech: ["JavaScript", "DOM Manipulation"],
    github: "https://github.com/antoniotagaruma8/ConditionalsGame",
    link: "https://conditionals-game.vercel.app",
    year: "2026",
    description: "Un juego arcade de aula diseñado para enseñar condicionales en inglés.",
    problem: "Los ejercicios de gramática para condicionales suelen ser tareas de hoja de trabajo secas y repetitivas.",
    solution: "Un juego web interactivo de estilo retro que hace que explorar cláusulas condicionales sea competitivo y divertido.",
  },
  {
    id: "reported-speech",
    title: "Actividad del habla informada",
    category: "Juegos EdTech",
    tech: ["JavaScript"],
    github: "https://github.com/antoniotagaruma8/ReportedSpeech",
    link: "https://reported-speech-kohl.vercel.app",
    year: "2026",
    description: "Un juego de aula con temática noticiosa para dominar el discurso indirecto.",
    problem: "Los estudiantes encuentran confusas y contraintuitivas las reglas de cambio de tiempo del discurso indirecto.",
    solution: "Una interfaz estilo juego de roles donde los estudiantes actúan como periodistas convirtiendo citas directas en noticias reportadas.",
  },
  {
    id: "passive-voice",
    title: "Actividad de voz pasiva",
    category: "Juegos EdTech",
    tech: ["JavaScript"],
    github: "https://github.com/antoniotagaruma8/passivevoiceactivity",
    link: "https://passivevoiceactivity.vercel.app",
    year: "2026",
    description: "Un juego estilo 'Tug of War' para practicar la voz pasiva versus activa.",
    problem: "Los estudiantes frecuentemente mezclan sujeto y objeto al formar oraciones pasivas.",
    solution: "Una mecánica visual de tira y afloja que refuerza el cambio gramatical entre estructuras activas y pasivas.",
  },
  {
    id: "follow-frog",
    title: "Sigue a la rana",
    category: "Juegos EdTech",
    tech: ["JavaScript", "HTML"],
    github: "https://github.com/antoniotagaruma8/FollowTheFrogActivity",
    link: "https://follow-the-frog-activity.vercel.app",
    year: "2026",
    description: "Una actividad interactiva de comprensión basada en la campaña de concienciación medioambiental 'Follow the Frog'.",
    problem: "Los ejercicios tradicionales de comprensión auditiva sobre sostenibilidad pueden parecer desconectados de los medios del mundo real.",
    solution: "Una lección web gamificada que utiliza la popular campaña de vídeo para evaluar la comprensión y el vocabulario en un formato atractivo.",
  },
  {
    id: "loan-word",
    title: "Detectives de palabras de préstamo",
    category: "Juegos EdTech",
    tech: ["JavaScript", "HTML"],
    github: "https://github.com/antoniotagaruma8/LoanWordDetectives",
    link: "https://loan-word-detectives.vercel.app",
    year: "2026",
    description: "Un atractivo juego lingüístico donde los estudiantes identifican palabras prestadas extranjeras en inglés.",
    problem: "Los estudiantes a menudo tienen dificultades para reconocer las raíces etimológicas, lo que puede dificultar la adquisición de vocabulario avanzado.",
    solution: "Un juego web con temática de detectives que hace que la exploración de los orígenes y la etimología de las palabras sea interactiva y gratificante.",
  },
  {
    id: "ph-cold-war",
    title: "PhDuringColdWar (juego de palabras)",
    category: "Juegos EdTech",
    tech: ["JavaScript", "HTML"],
    github: "https://github.com/antoniotagaruma8/PhDuringColdWar",
    link: "https://ph-during-cold-war.vercel.app",
    year: "2026",
    description: "Un juego interactivo de exploración histórica sobre Filipinas durante la Guerra Fría.",
    problem: "Los estudiantes a menudo encuentran secas y difíciles de conectar las lecciones de historia de los libros de texto sobre la era de la Guerra Fría.",
    solution: "Una experiencia web interactiva con temática de archivos desclasificados que da vida a eventos históricos a través de la exploración gamificada.",
  },
  {
    id: "lesson-hub",
    title: "Centro de clases y lecciones",
    category: "UI y Apps",
    tech: ["TypeScript", "Next.js"],
    github: "https://github.com/antoniotagaruma8/lesson-hub",
    link: "https://classhub-seven.vercel.app",
    year: "2026",
    description: "Un panel de gestión y archivo centralizado para los recursos del aula.",
    problem: "Los materiales educativos se fragmentan en unidades locales y almacenamiento en la nube durante un semestre.",
    solution: "Un portal Next.js claramente organizado que actúa como una única fuente de información para estudiantes y profesores.",
  },
  {
    id: "mooc-final",
    title: "Proyecto Final MOOC",
    category: "Académico",
    tech: ["SCSS", "HTML"],
    github: "https://github.com/antoniotagaruma8/MOOCFinalProject",
    link: "https://mooc-final-project.vercel.app",
    year: "2026",
    description: "Un trabajo final de educación comparada que analiza metodologías de enseñanza globales.",
    problem: "Sintetizar grandes volúmenes de datos educativos comparativos en un formato legible es un desafío.",
    solution: "Un portal académico responsivo de estilo SCSS que presenta investigaciones complejas de forma clara y hermosa.",
  },
  {
    id: "tech-education",
    title: "Blog de tecnología en educación",
    category: "Académico",
    tech: ["HTML", "CSS"],
    github: "https://github.com/antoniotagaruma8/techineducation",
    link: "https://techineducation.vercel.app",
    year: "2026",
    description: "Una presentación interactiva sobre el desarrollo web asistido por IA en la educación.",
    problem: "Los educadores carecen de recursos accesibles sobre cómo integrar herramientas modernas de inteligencia artificial en su flujo de trabajo docente.",
    solution: "Una aplicación web dinámica basada en diapositivas que demuestra visualmente integraciones prácticas de IA.",
  },
  {
    id: "pdf-editor",
    title: "Editor de PDF Interactivo",
    category: "UI y Apps",
    tech: ["HTML5", "Canvas API", "PDF.js", "Fabric.js"],
    github: "https://github.com/antoniotagaruma8",
    link: "/es/coming-soon",
    year: "2026",
    description: "Una herramienta ligera de navegador sin instalación para proyectar y anotar hojas de trabajo en PDF en pizarras inteligentes.",
    problem: "Los profesores necesitan anotar PDFs en clase pero carecen de acceso a costoso software propietario en los ordenadores del colegio.",
    solution: "Un renderizador de PDF del lado del cliente con una capa de dibujo transparente de Fabric.js para anotación en tiempo real sin subidas al servidor.",
  },
  {
    id: "interactive-drawing",
    title: "Pizarra de Dibujo Interactiva",
    category: "UI y Apps",
    tech: ["HTML5", "Canvas API", "PointerEvents API"],
    github: "https://github.com/antoniotagaruma8",
    link: "/es/coming-soon",
    year: "2026",
    description: "Una pizarra digital optimizada para uso táctil diseñada para pizarras inteligentes de educación primaria.",
    problem: "El software de pizarra comercial es demasiado pesado y lento para los trazos rápidos de los dedos de los niños pequeños en el hardware escolar.",
    solution: "Una aplicación de dibujo basada en Canvas de latencia cero con controles simplificados y codificados por colores diseñados para las habilidades motoras de los niños.",
  },
  {
    id: "trivia-bingo",
    title: "EdTech Trivia Bingo",
    category: "Juegos EdTech",
    tech: ["Node.js", "Socket.io", "Gemini AI", "Express"],
    github: "",
    link: "",
    year: "2026",
    description: "Un juego de bingo de trivia multijugador en tiempo real con preguntas generadas por IA alineadas con el plan de estudios.",
    problem: "Los profesores necesitan herramientas de evaluación atractivas que combinen jugabilidad competitiva con contenido relevante del plan de estudios.",
    solution: "Una plataforma de bingo con WebSocket donde Gemini AI genera dinámicamente preguntas de trivia sobre cualquier tema para sesiones en vivo en el aula.",
  }
];

export const archiveData = {
  en: archiveDataEN,
  es: archiveDataES
};

